## Accident prediction

### Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
ds = pd.read_csv("accident.csv")
ds.replace({"Male": 0, "Female": 1, "No": 0, "Yes": 1}, inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_15372\3777825793.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ds.replace({"Male": 0, "Female": 1, "No": 0, "Yes": 1}, inplace=True)


In [3]:
print(ds)

     Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0     56     1.0             27.0            0              0         1
1     69     1.0             46.0            0              1         1
2     46     0.0             46.0            1              1         0
3     32     0.0            117.0            0              1         0
4     60     1.0             40.0            1              1         0
..   ...     ...              ...          ...            ...       ...
195   69     1.0            111.0            0              1         1
196   30     1.0             51.0            0              1         1
197   58     0.0            110.0            0              1         1
198   20     0.0            103.0            0              1         1
199   56     1.0             43.0            0              1         1

[200 rows x 6 columns]


In [4]:
X = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values
print(X)
print(y)

[[ 56.   1.  27.   0.   0.]
 [ 69.   1.  46.   0.   1.]
 [ 46.   0.  46.   1.   1.]
 [ 32.   0. 117.   0.   1.]
 [ 60.   1.  40.   1.   1.]
 [ 25.   0.  49.   1.   1.]
 [ 38.   0. 116.   1.   1.]
 [ 56.   0.  47.   1.   1.]
 [ 36.   1.  83.   1.   0.]
 [ 40.   1. 116.   1.   0.]
 [ 28.   1.  88.   0.   1.]
 [ 28.   0.  80.   1.   1.]
 [ 41.   0.  67.   1.   0.]
 [ 53.   1.  38.   1.   1.]
 [ 57.   1.  23.   0.   1.]
 [ 41.   1.  nan   0.   0.]
 [ 20.   1.  83.   1.   1.]
 [ 39.   0.  68.   0.   0.]
 [ 19.   1.  36.   1.   1.]
 [ 41.   0.  nan   1.   0.]
 [ 61.   1. 111.   0.   0.]
 [ 47.   0.  49.   1.   0.]
 [ 55.   1. 112.   0.   1.]
 [ 19.   1.  65.   0.   0.]
 [ 38.   1.  25.   1.   1.]
 [ 50.   1. 118.   1.   1.]
 [ 29.   0.  56.   0.   1.]
 [ 39.   1.  43.   1.   1.]
 [ 61.   0. 112.   1.   0.]
 [ 42.   0.  nan   1.   0.]
 [ 66.  nan  72.   0.   1.]
 [ 44.   0. 114.   0.   1.]
 [ 59.   1. 118.   1.   0.]
 [ 45.   0.  79.   0.   1.]
 [ 33.   0. 116.   0.   0.]
 [ 32.   0.  82.   0

In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:4])
X[:, 0:4] = imputer.transform(X[:, 0:4])
print(X)

[[ 56.           1.          27.           0.           0.        ]
 [ 69.           1.          46.           0.           1.        ]
 [ 46.           0.          46.           1.           1.        ]
 [ 32.           0.         117.           0.           1.        ]
 [ 60.           1.          40.           1.           1.        ]
 [ 25.           0.          49.           1.           1.        ]
 [ 38.           0.         116.           1.           1.        ]
 [ 56.           0.          47.           1.           1.        ]
 [ 36.           1.          83.           1.           0.        ]
 [ 40.           1.         116.           1.           0.        ]
 [ 28.           1.          88.           0.           1.        ]
 [ 28.           0.          80.           1.           1.        ]
 [ 41.           0.          67.           1.           0.        ]
 [ 53.           1.          38.           1.           1.        ]
 [ 57.           1.          23.           0.   

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.svm import SVC

classifier = SVC(kernel="sigmoid", random_state=0, coef0=0.1)
classifier.fit(X_train, y_train)

SVC(coef0=0.1, kernel='sigmoid', random_state=0)

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[5 2]
 [4 9]]


0.7